// Полный список языков (ISO 639-1) для словаря. Отдельно от constants/languages.js
// (тот — короткий список для профиля, его не трогаем). Каждый элемент:
// { code (ISO), name (англ.), native (родное написание) }.
export const ISO_LANGUAGES = [
  { code: 'ab', name: 'Abkhaz', native: 'аҧсуа' },
  { code: 'aa', name: 'Afar', native: 'Afaraf' },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans' },
  { code: 'ak', name: 'Akan', native: 'Akan' },
  { code: 'sq', name: 'Albanian', native: 'Shqip' },
  { code: 'am', name: 'Amharic', native: 'አማርኛ' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'an', name: 'Aragonese', native: 'Aragonés' },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն' },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া' },
  { code: 'av', name: 'Avaric', native: 'авар мацӀ' },
  { code: 'ay', name: 'Aymara', native: 'aymar aru' },
  { code: 'az', name: 'Azerbaijani', native: 'azərbaycan dili' },
  { code: 'bm', name: 'Bambara', native: 'bamanankan' },
  { code: 'ba', name: 'Bashkir', native: 'башҡорт теле' },
  { code: 'eu', name: 'Basque', native: 'euskara' },
  { code: 'be', name: 'Belarusian', native: 'беларуская' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'bh', name: 'Bihari', native: 'भोजपुरी' },
  { code: 'bi', name: 'Bislama', native: 'Bislama' },
  { code: 'bs', name: 'Bosnian', native: 'bosanski jezik' },
  { code: 'br', name: 'Breton', native: 'brezhoneg' },
  { code: 'bg', name: 'Bulgarian', native: 'български език' },
  { code: 'my', name: 'Burmese', native: 'ဗမာစာ' },
  { code: 'ca', name: 'Catalan', native: 'català' },
  { code: 'ch', name: 'Chamorro', native: 'Chamoru' },
  { code: 'ce', name: 'Chechen', native: 'нохчийн мотт' },
  { code: 'ny', name: 'Chichewa', native: 'chiCheŵa' },
  { code: 'zh', name: 'Chinese', native: '中文' },
  { code: 'cv', name: 'Chuvash', native: 'чӑваш чӗлхи' },
  { code: 'kw', name: 'Cornish', native: 'Kernewek' },
  { code: 'co', name: 'Corsican', native: 'corsu' },
  { code: 'hr', name: 'Croatian', native: 'hrvatski jezik' },
  { code: 'cs', name: 'Czech', native: 'čeština' },
  { code: 'da', name: 'Danish', native: 'dansk' },
  { code: 'dv', name: 'Divehi', native: 'ދިވެހި' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands' },
  { code: 'dz', name: 'Dzongkha', native: 'རྫོང་ཁ' },
  { code: 'en', name: 'English', native: 'English' },
  { code: 'eo', name: 'Esperanto', native: 'Esperanto' },
  { code: 'et', name: 'Estonian', native: 'eesti' },
  { code: 'ee', name: 'Ewe', native: 'Eʋegbe' },
  { code: 'fo', name: 'Faroese', native: 'føroyskt' },
  { code: 'fj', name: 'Fijian', native: 'vosa Vakaviti' },
  { code: 'fi', name: 'Finnish', native: 'suomi' },
  { code: 'fr', name: 'French', native: 'français' },
  { code: 'ff', name: 'Fula', native: 'Fulfulde' },
  { code: 'gl', name: 'Galician', native: 'Galego' },
  { code: 'ka', name: 'Georgian', native: 'ქართული' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά' },
  { code: 'gn', name: 'Guaraní', native: 'Avañeẽ' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'ht', name: 'Haitian Creole', native: 'Kreyòl ayisyen' },
  { code: 'ha', name: 'Hausa', native: 'هَوُسَ' },
  { code: 'he', name: 'Hebrew', native: 'עברית' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'hu', name: 'Hungarian', native: 'magyar' },
  { code: 'ia', name: 'Interlingua', native: 'Interlingua' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'ga', name: 'Irish', native: 'Gaeilge' },
  { code: 'ig', name: 'Igbo', native: 'Asụsụ Igbo' },
  { code: 'is', name: 'Icelandic', native: 'Íslenska' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
  { code: 'iu', name: 'Inuktitut', native: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'jv', name: 'Javanese', native: 'basa Jawa' },
  { code: 'kl', name: 'Kalaallisut', native: 'kalaallisut' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'kk', name: 'Kazakh', native: 'қазақ тілі' },
  { code: 'km', name: 'Khmer', native: 'ខ្មែរ' },
  { code: 'rw', name: 'Kinyarwanda', native: 'Ikinyarwanda' },
  { code: 'ky', name: 'Kyrgyz', native: 'Кыргызча' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'ku', name: 'Kurdish', native: 'Kurdî' },
  { code: 'la', name: 'Latin', native: 'latine' },
  { code: 'lb', name: 'Luxembourgish', native: 'Lëtzebuergesch' },
  { code: 'lg', name: 'Ganda', native: 'Luganda' },
  { code: 'ln', name: 'Lingala', native: 'Lingála' },
  { code: 'lo', name: 'Lao', native: 'ພາສາລາວ' },
  { code: 'lt', name: 'Lithuanian', native: 'lietuvių kalba' },
  { code: 'lv', name: 'Latvian', native: 'latviešu valoda' },
  { code: 'gv', name: 'Manx', native: 'Gaelg' },
  { code: 'mk', name: 'Macedonian', native: 'македонски јазик' },
  { code: 'mg', name: 'Malagasy', native: 'fiteny malagasy' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'mt', name: 'Maltese', native: 'Malti' },
  { code: 'mi', name: 'Māori', native: 'te reo Māori' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'mn', name: 'Mongolian', native: 'Монгол хэл' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली' },
  { code: 'nb', name: 'Norwegian Bokmål', native: 'Norsk Bokmål' },
  { code: 'nn', name: 'Norwegian Nynorsk', native: 'Norsk Nynorsk' },
  { code: 'no', name: 'Norwegian', native: 'Norsk' },
  { code: 'oc', name: 'Occitan', native: 'occitan' },
  { code: 'om', name: 'Oromo', native: 'Afaan Oromoo' },
  { code: 'or', name: 'Oriya', native: 'ଓଡ଼ିଆ' },
  { code: 'os', name: 'Ossetian', native: 'ирон æвзаг' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'ps', name: 'Pashto', native: 'پښتو' },
  { code: 'fa', name: 'Persian', native: 'فارسی' },
  { code: 'pl', name: 'Polish', native: 'Polski' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'qu', name: 'Quechua', native: 'Runa Simi' },
  { code: 'rm', name: 'Romansh', native: 'rumantsch grischun' },
  { code: 'ro', name: 'Romanian', native: 'Română' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'sa', name: 'Sanskrit', native: 'संस्कृतम्' },
  { code: 'sd', name: 'Sindhi', native: 'सिन्धी' },
  { code: 'se', name: 'Northern Sami', native: 'Davvisámegiella' },
  { code: 'sm', name: 'Samoan', native: 'gagana faa Samoa' },
  { code: 'sr', name: 'Serbian', native: 'српски језик' },
  { code: 'gd', name: 'Scottish Gaelic', native: 'Gàidhlig' },
  { code: 'sn', name: 'Shona', native: 'chiShona' },
  { code: 'si', name: 'Sinhala', native: 'සිංහල' },
  { code: 'sk', name: 'Slovak', native: 'slovenčina' },
  { code: 'sl', name: 'Slovene', native: 'slovenski jezik' },
  { code: 'so', name: 'Somali', native: 'Soomaaliga' },
  { code: 'st', name: 'Southern Sotho', native: 'Sesotho' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'su', name: 'Sundanese', native: 'Basa Sunda' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
  { code: 'sv', name: 'Swedish', native: 'Svenska' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'tg', name: 'Tajik', native: 'тоҷикӣ' },
  { code: 'th', name: 'Thai', native: 'ไทย' },
  { code: 'ti', name: 'Tigrinya', native: 'ትግርኛ' },
  { code: 'bo', name: 'Tibetan', native: 'བོད་ཡིག' },
  { code: 'tk', name: 'Turkmen', native: 'Türkmen' },
  { code: 'tl', name: 'Tagalog', native: 'Wikang Tagalog' },
  { code: 'tn', name: 'Tswana', native: 'Setswana' },
  { code: 'to', name: 'Tonga', native: 'faka Tonga' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe' },
  { code: 'tt', name: 'Tatar', native: 'татар теле' },
  { code: 'ug', name: 'Uyghur', native: 'ئۇيغۇرچە' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbek' },
  { code: 've', name: 'Venda', native: 'Tshivenḓa' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'vo', name: 'Volapük', native: 'Volapük' },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg' },
  { code: 'wo', name: 'Wolof', native: 'Wollof' },
  { code: 'fy', name: 'Western Frisian', native: 'Frysk' },
  { code: 'xh', name: 'Xhosa', native: 'isiXhosa' },
  { code: 'yi', name: 'Yiddish', native: 'ייִדיש' },
  { code: 'yo', name: 'Yoruba', native: 'Yorùbá' },
  { code: 'zu', name: 'Zulu', native: 'isiZulu' },
]

// Быстрый поиск по коду: LANG_BY_CODE.get('pl') → { code, name, native }
export const LANG_BY_CODE = new Map(ISO_LANGUAGES.map((l) => [l.code, l]))

// Человеческое имя по коду ('pl' → 'Polish'). Неизвестный/пустой код возвращаем как есть.
export const langName = (code) => LANG_BY_CODE.get(code)?.name || code || '—'
